### ISSUE TITLE
Get rid of trash-files  (add to .gitignore)

### ISSUE THREAD

**Issue by aMFeriuSS** [shayenblue/forkify#1]
`.DS_Store` (mac-os finder's temp-file) founded.
Maybe there are more =)

**Comment by aMFeriuSS** [comment]
Something like this (for .gitignore)
```
# System Files
.DS_Store
Thumbs.db
```
Check common `.gitignore` files for js+html projects

**Comment by shayenblue** [comment]
Done)

**Comment by aMFeriuSS** [comment]
Nice! Catch a star)
